# Use official PostgreSQL image
FROM postgres:latest

# Set environment variables used in prisma service
ENV POSTGRES_DB = database_name 
ENV POSTGRES_USER = username
ENV POSTGRES_PASSWORD = password

# Expose the PostgreSQL port
EXPOSE 5432