services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  backend:
    build: .
    ports:
      - '4200:4200'
    depends_on:
      - database
    env_file:
      - .env
